### ISSUE TITLE
[PR Bug] Shared library 에서 심볼을 찾지 못하는 이슈

### ISSUE THREAD

**Issue by kimminkyeu** [42Chimera/chimera#5]
---
# 풀리퀘 브랜치에서 발생한 이슈입니다

### `sh GenerateProjectFIles.sh` 를 처음 실행하면, scop이 빌드되지 않습니다.
1. 기존에 생성되있는 ChimeraEngineCore.so/dll/dylib를 지웁니다. 
2. `sh GenerateProjectFIles.sh` 실행 --> ChimeraEngineCore 동적 라이브러리 생성 (  engine/binary 경로에 생성 )
3. `cd scop && sh setup.sh` 실행 --> ChimeraEngineCore 링킹 과정에서 아래와 같은 오류 발생
```bash
/usr/bin/ld: CMakeFiles/Scop.dir/source/Scop.cpp.o: in function `main':
/home/kyeu/goinfree/chimera/scop/source/Scop.cpp:25: undefined reference to `Cm::Application::Run()'
/usr/bin/ld: CMakeFiles/Scop.dir/source/Scop.cpp.o: in function `Scop::Scop()':
/home/kyeu/goinfree/chimera/scop/source/Scop.cpp:10: undefined reference to `Cm::Application::Application()'
/usr/bin/ld: /home/kyeu/goinfree/chimera/scop/source/Scop.cpp:14: undefined reference to `Cm::Application::~Application()'
/usr/bin/ld: CMakeFiles/Scop.dir/source/Scop.cpp.o: in function `Scop::~Scop()':
/home/kyeu/goinfree/chimera/scop/source/Scop.cpp:6: undefined reference to `Cm::Application::~Application()'
/usr/bin/ld: CMakeFiles/Scop.dir/source/Scop.cpp.o:(.data.rel.ro._ZTI4Scop[_ZTI4Scop]+0x10): undefined reference to `typeinfo for Cm::Application'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/Scop.dir/build.make:97: Scop] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/Scop.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
```
### 그런데, `sh GenerateProjectFIles.sh` 를 다시 실행하면, 문제 없이 scop이 빌드 됩니다.
---
## 문제 원인
CMakeLIst.txt의 설정 오류로 링킹 과정에 문제가 있거나
ChimeraEngineCore 동적 라이브러리 생성 과정에서 문제가 있거나
아직 이슈 원인을 파악하지 못했습니다....

@learnershigh @flowjiyun

**Comment by flowjiyun** [comment]
@kimminkyeu 해당 부분 지금 저도 확인해보고 원인 찾아 보겠습니다ㅜㅜ

**Comment by kimminkyeu** [comment]
@flowjiyun 현재 날린 풀리퀘스트에서 확인한 이슈입니다! 저도 원인 찾아보고, 고친 뒤에 머지하도록 하겠습니다 ㅠ

**Comment by kimminkyeu** [comment]
@flowjiyun 원인 찾았습니다.
file(GLOB foo.dylib) 이런 식으로 라이브러리 파일을 찾아서,  ChimeraEngineCore_LIBRARIES 변수에 저장하는데,
최초에 실행시엔 아직 foo.dylib이 생성되지 않아 ChimeraEngineCore_LIBRARIES 변수에 아무것도 안들어가는 거였네요!
(두번쨰 실행할땐 foo.dylib이 있기 떄문에 경로 세팅이 됨)
고치고 코드리뷰 요청 드리겠습니다!
